services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: adonis-backend
    ports:
      - "3333:3333"
    environment:
      TZ: UTC
      PORT: 3333
      HOST: "0.0.0.0"
      LOG_LEVEL: info
      APP_KEY: 4G28h2DdHB3y5tfLU7NgCxpWDD7UbMR2
      SESSION_DRIVER: cookie
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: "http://adonis-backend:3333"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
